on:
  push:
    branches:
      - main
      - login-gcr.io # @note: use any development branch you would like

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'ci-cd-pipeline-markkraus'
          workload_identity_provider: 'projects/892886010280/locations/global/workloadIdentityPools/github/providers/my-new-repo'
          create_credentials_file: true
          export_environment_variables: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      # Configure Docker to authenticate with GCP
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      # Build and Push Docker Image using regular Docker commands
      - name: Build and Push Without Buildx
        run: |
          docker build -t us-east1-docker.pkg.dev/ci-cd-pipeline-markkraus/build-and-push-image-markkraus/my-image:latest .
          docker push us-east1-docker.pkg.dev/ci-cd-pipeline-markkraus/build-and-push-image-markkraus/my-image:latest
